workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      xcode: latest
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Expo prebuild
        script: |
          chmod +x node_modules/.bin/expo
          npx expo prebuild --platform android
      - name: Fix Hermes permissions
        script: |
          chmod +x node_modules/react-native/sdks/hermesc/linux64-bin/hermesc
      - name: Build APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk